import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Header} from "@/layout/Header";
import Providers from "@/providers/Providers";
import Box from "@mui/joy/Box";
import {Sheet} from "@mui/joy";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={inter.className}
            style={{
                display: 'flex',
                placeItems: 'center',
                flexDirection: 'column',
                margin: 0,
                width: '100vw',
                height: '100dvh',
                // maxWidth: '1000px',
                overflowX: 'hidden',

            }}
        >
        <div style={{
            maxWidth: '100vw',

        }}>
            <Header/>
            <main>
                <Providers>
                    <div
                        style={{
                            maxWidth: '1000px',
                            margin: '0',
                            padding: '0',
                            width: '100%',
                            // height: '100dvh',
                            // flex: '1 0 auto',
                            background: 'rgb(227, 251, 227)',
                        }}
                    >
                        {children}
                    </div>
                </Providers>
            </main>

        </div>
        </body>
        </html>
    );
}
