import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Header} from "@/layout/Header";
import Providers from "@/providers/Providers";
import Box from "@mui/joy/Box";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={inter.className}
            style={{
                display: 'flex',
                placeItems: 'center',
                flexDirection: 'column',
            }}
        >
        <Header/>
        <main>
            <Providers>
                <Box
                    sx={{
                        maxWidth: '1000px'
                    }}
                >
                    {children}
                </Box>
            </Providers>
        </main>

        </body>
        </html>
    );
}
